search form
vladiklem/sedona pull request #2
Opened 2018-11-28 11:56 UTC by vladiklem

2018-11-28 14:30 UTC, Rasoft2311 commented on styles/components/search-form-container.scss
> +  width: 100%;
width:100% ни на что не влияет

2018-11-28 14:30 UTC, Rasoft2311 commented on styles/components/search-form-container.scss
> +  height: auto;
min-height: 217px; height: auto; также, я б их убрал

2018-11-28 14:30 UTC, Rasoft2311 commented on styles/components/search-form-container.scss
> +  }
не треба цього

2018-11-28 14:30 UTC, Rasoft2311 commented on styles/components/search-form-container.scss
> +
Створи елемент інпут type range

2018-11-28 15:47 UTC, kryvonos-v commented on sedona-hotels.html
> +    <section class="search-form-container position-relative">
Назва хороша, але можливо занадто довга, тому я б залишив `search-form`

2018-11-28 15:49 UTC, kryvonos-v commented on sedona-hotels.html
> +    <section class="search-form-container position-relative">
`position-relative` хороша назва для CSS утиліти, але я зробив б просто `relative` як це зробили у [tailwind](https://tailwindcss.com/docs/positioning/#app)

2018-11-28 16:20 UTC, kryvonos-v commented on sedona-hotels.html
> +            <label class="fieldset-wrapper__checkbox-wrapper checkbox-wrapper" for="infrastructure-pool">
`checkbox-wrapper` хороша назва, але я постарався б зробити ще коротшою `checkbox`

2018-11-28 16:22 UTC, kryvonos-v commented on sedona-hotels.html
> +            <label class="fieldset-wrapper__checkbox-wrapper checkbox-wrapper" for="infrastructure-pool">
Ти використав клас `fieldset-wrapper__checkbox-wrapper` для того щоб задати відступи знизу для чекбокса. Ти все правильно зробив, але швидше всьго тобі у майбутньому знову доведеться додавати margin знизу для чекбокса, тому ти можеш для цього створити окрему утиліту
```css
.mb-checkbox {
  margin-bottom: 23px;
}
```

2018-11-30 10:52 UTC, kryvonos-v commented on sedona-hotels.html
> +        <div class="search-form-container__checkboxes">
Спробуй обійтися без цього div'a (обгортка)

2018-11-30 10:52 UTC, kryvonos-v commented on sedona-hotels.html
> +          <legend class="fieldset-wrapper__name">тип жилья:</legend>
`тип` => `Тип`

2018-11-30 11:15 UTC, kryvonos-v commented on sedona-hotels.html
> +          <legend class="fieldset-wrapper__name">стоимость в сутки (Р):</legend>
`стоимость` => `Стоимость`

2018-11-30 11:15 UTC, kryvonos-v commented on sedona-hotels.html
> +          <button class="fieldset-wrapper__show-button">показать</button>
`показать` => `Показать`

2018-11-30 11:16 UTC, kryvonos-v commented on sedona-hotels.html
>          <input type="radio" id="sort-rating" name="rating"/><label for="sort-rating">по рейтингу</label>
`по` => `По`

2018-11-30 11:35 UTC, kryvonos-v commented on styles/components/search-form-container.scss
> +  width: 224px;
Краще поставити `width: 100%;` і `max-width: 320px;`, тоді взагалі можна видалити код на 98 рядку

2018-11-30 11:36 UTC, kryvonos-v commented on styles/components/search-form-container.scss
> +    width: 320px;
Ось це можна видалити. Дивись на попередній коментар

2018-11-30 11:46 UTC, kryvonos-v requested changes
![alt text](https://i.ibb.co/y0XC6bx/Screen-Shot-2018-11-30-at-1-03-10-PM.png)
1. Зробити відступи як на макеті
2. Зробити заокруглення як на макеті
3. Зробити padding’и як на макеті
4. Зробити uppercase як на макеті

Зроби щоб для мобільних пристроїв форма виглядала ось так:

![Вигляд форми для пошуку готелів на мобільних пристроях](https://i.ibb.co/7yJMM3x/Screen-Shot-2018-11-30-at-12-47-05-PM.png)
Вигляд форми починаючи з `350px`:

![Вигляд форми для великих мобільних пристроїв](https://i.ibb.co/Sd0qnHw/Screen-Shot-2018-11-30-at-12-50-02-PM.png)

Загалом код гарно написаний і я не знайшов ніяких грубих помилок, окрім змінення значення зміною у файлах bulma ;)

2018-12-03 13:25 UTC, kryvonos-v approved these changes

2018-12-03 15:27 UTC, merged