filter menu
vladiklem/sedona pull request #3
Opened 2018-11-28 23:30 UTC by vladiklem

2018-11-29 14:14 UTC, valeriiamykhalova reviewed
Все чотінько по БЕМу, не має до чого докопатись 👍

2018-11-29 14:14 UTC, emerell commented on styles/components/filter-menu.scss
> +    padding: 33px 46px;
Зроби ще ```@include desctop {}``` і пропиши там падінги зліва і справа по 73px. Там на макеті **sedona-hotels-1200** вони трохи більші за ті, які у десктопів

2018-11-29 14:14 UTC, emerell commented on sedona-hotels.html
> +      <fieldset class="show-options" form="search-form">
Подивись на відстань на макеті між **arrow-up** і **arrow-down**, я б її збільшила для десктопів

2018-12-01 15:46 UTC, taran-d requested changes

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  margin-bottom: 31px;
Ми не присвоюємо margin блокам по BEM, тому краще додай ще один клас filter-menu__sort-options і зроби цей філдсет і блоком і елементом. А саме в елемент винеси margin.

2018-12-01 15:46 UTC, Rasoft2311 commented on sedona-hotels.html
> +      <fieldset class="sort-options" form="search-form">
Ти додавав класу sort-options margin, я описав це знизу. По Бем так не можна, додай тут клас filter-menu__sort-options( зроби його не тільки блоком, а й елементом) і туди винеси margin

2018-12-01 15:46 UTC, Rasoft2311 commented on sedona-hotels.html
> +          <input class="sort-options__input" type="radio" id="sort-price" name="sort" checked/><label class="sort-options__label" for="sort-price">по цене</label>
Якщо елементів інпута більше ніж 1, то name позначає назву цієї групи, а далі у кожного інпута ще має бути атрибут value, щоб відзначити їх унікальну назву. Якщо, наприклад, у нас просто є один input type="checkbox", то йому ми даємо тільки name ( він буде як value у минулому випадку ) . Пропиши тут щось типу value="price"

2018-12-01 15:46 UTC, Rasoft2311 commented on sedona-hotels.html
> +          <input class="sort-options__input" type="radio" id="sort-type" name="sort"/><label class="sort-options__label" for="sort-type">по типу</label>
value="type"

2018-12-01 15:46 UTC, Rasoft2311 commented on sedona-hotels.html
> +          <input class="sort-options__input" type="radio" id="sort-rating" name="sort"/><label class="sort-options__label" for="sort-rating">по рейтингу</label>
value="rating"

2018-12-01 15:46 UTC, Rasoft2311 commented on sedona-hotels.html
> +        <label for="arrow-up"><input class="show-options__input" type="radio" id="arrow-up" name="show-options"/><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="11" height="10"><path class
value="ascending" ( "asc" )

2018-12-01 15:46 UTC, Rasoft2311 commented on sedona-hotels.html
> +        <label for="arrow-down"><input class="show-options__input" type="radio" id="arrow-down" name="show-options" checked/><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="11" height="10"
value="desc" (descending)

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  flex-direction: column;
Ти для всіх екранів ставиш flex-direction:column, а потім трохи нижче для tablet{flex-direction-row} і виходить в тебе перезапис, коли відкривається сайт на таблетах і вище. Забери звідси flex-direction: column і виведи його в mobile{}, тоді в таблета взагалі можна буде прибрати рядок flex-direction:row , оскільки воно стоїть за замовчуванням

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  padding: 15px;
Те саме з падінгом, переведи його в mobile. Все, що треба для мобілок, виводимо в mobile

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  margin: 32px 0;
знову, margin виведи в mobile

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +    margin-right: 50px;
margin: 0 50px 0 0;

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  margin-bottom: 31px;
І виведи його ще окремо в mobile

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  margin: 5px 10px;
В mobile

2018-12-01 15:46 UTC, Rasoft2311 commented on styles/components/filter-menu.scss
> +  padding-bottom: 15px;
В mobile

2018-12-02 14:43 UTC, kryvonos-v commented on styles/components/filter-menu.scss
> +    margin-right: 50px;
Те як Влад написав теж нормальний варіант

2018-12-02 14:46 UTC, kryvonos-v commented on sedona-hotels.html
> +      <h2 class="filter-menu__name">найдено:<span>3</span></h2>
`найдено` => `Найдено` і постав пробіл після `:`

2018-12-02 14:50 UTC, kryvonos-v commented on styles/components/filter-menu.scss
> +.sort-options{
Якщо ти зробив `sort-options` БЕМ блоком, то тоді потрібно його винести в окремий файл

2018-12-02 14:51 UTC, kryvonos-v commented on styles/main.css
> +  color: #b1b1b1;
Колір потрібно винести у sass змінну

2018-12-02 14:54 UTC, kryvonos-v commented on styles/components/filter-menu.scss
> +  display: flex;
Для мобільних пристроїв взагалі можна обійтися без flexbox. Тобі достатньо тут написати:
```scss
.filter-menu {
  @include mobile {
    text-align: center;
  }
}

2018-12-02 15:00 UTC, kryvonos-v commented on sedona-hotels.html
> +        <span class="sort-options__criterion">
Цей блок можна переписати ось таким чином:
```html
<label class="sort-options__criterion">
  <input class="sort-options__input" type="radio" name="sort" value="price" checked>
  <span class="sort-options__label">По цене</span>
</label>
```
Тоді тобі не буде потрібно прописувати теги `id` i `for`

2018-12-02 15:03 UTC, kryvonos-v commented on sedona-hotels.html
> +        <label for="arrow-up"><input class="show-options__input" type="radio" id="arrow-up" name="show-options"/><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="11" height="10"><path class
Коли ти вставляєш svg на пряму у html документ, то `xmlns="http://www.w3.org/2000/svg"` атрибут можна видалити

2018-12-02 15:04 UTC, kryvonos-v commented on styles/components/filter-menu.scss
> +
Ти у цьому файлі ще використовував змінні для кольорів, тому пропиши явно звідки вони у тебе беруться:
```scss
@import "../units/colors/utils";
```

2018-12-02 15:07 UTC, kryvonos-v requested changes
Вигляд фільтрів на мобільних пристроях:

![Меню с фильтрами](https://i.ibb.co/QQLwg94/Screen-Shot-2018-12-02-at-5-08-13-PM.png)

Зроби, будь ласка, що для взагалі маленьких екранів всі елементи ставали у колонку одне за одним.

Взагалі код гарно написаний і як то кажуть "результат на лице". Молодець)

2018-12-03 15:58 UTC, merged