search results
vladiklem/sedona pull request #4
Opened 2018-11-30 12:06 UTC by vladiklem

Разьебите!

2018-12-01 16:18 UTC, taran-d requested changes

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  padding: 15px 0;
flex-direction: column;
  padding: 15px 0; переведи в mobile

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +    flex-direction: row;
можно убрать, если добавишь mobile

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  margin-bottom: 10px;
можно вывести в mobile, тогда в таблете не надо будет обнулять margin-bottom:0

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  margin-top: 10px;
margin-bottom: 10px;
  text-align: center;
  margin-top: 10px; в mobile, что б не было перезаписи

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  justify-content: center;
в mobile и в tablet можно будет не писать   justify-content: flex-start; оно по умолчанию стоит

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  justify-content: center;
как и в коменте выше

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  padding: 3.5px 8px;
В mobile

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  margin-right: 40px;
В mobile

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +    margin-right: 0;
если выполнишь пред комент, можно будет не писать  margin-right: 0;

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +  padding: 3px 9.5px;
В mobile

2018-12-01 16:18 UTC, Rasoft2311 commented on styles/components/search-results.scss
> +.result-list-item__img-wrapper{
Владос, на макете у img всегда высота 90 px, у тебя для таблетов и выше она больше, поиграйся с отступами, что б  сделать, как на макете

2018-12-01 17:56 UTC, valeriiamykhalova approved these changes

2018-12-01 17:56 UTC, emerell commented on sedona-hotels.html
> +              <a class="button button--about" href="#">подробнее</a>
Краще з великої літери писати (подробнее -> Подробнее)

2018-12-03 13:03 UTC, kryvonos-v commented on sedona-hotels.html
> +        <li class="search-results__item result-list-item">
Побачив по стилях, що ти ніяк не використовуєш клас`.search-results__item`. Тому його можна видалити

2018-12-03 13:13 UTC, kryvonos-v commented on styles/components/search-results.scss
> +  color: #000;
У макеті стоїть інший колір

2018-12-03 13:17 UTC, kryvonos-v commented on styles/components/search-results.scss
> +.result-list-item{
Цей БЕМ блок потрібно винести в окремий файл `.result-list-item`. Ми це робимо для того щоб потім швидко і легко знаходити потрібні стилі

2018-12-03 13:18 UTC, kryvonos-v commented on styles/components/search-results.scss
> +.button{
Цей БЕМ блок потрібно винести в окремий файл `components/button.scss`. Ми це робимо для того щоб потім швидко і легко знаходити потрібні стилі

2018-12-03 13:20 UTC, kryvonos-v reviewed
Дивись тут абсолютно достатньо місця для того щоб відобразити інформацію про готель в один рядок:

![screen shot 2018-12-03 at 3 14 53 pm](https://user-images.githubusercontent.com/29276196/49376112-dd58fe80-f70e-11e8-9d21-d0c55313d201.png)

Тому задай стилі так, щоб інфомрція про готель відображалася у стовпчик лише до того моменту доки недостатньо місця для того щоб зробити це у рядок

2018-12-03 13:24 UTC, kryvonos-v requested changes
Є маленькі нюанси, але загалом дуже добре, по БЕМу взагалі пушка))

2018-12-03 17:03 UTC, merged